name: dotnet

on:
  push:
    paths:
      - "dotnet/**"

env:
  DAGGER_LOG_FORMAT: plain
  REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}

jobs:
  dotnet-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: dotnet build
        uses: dagger/dagger-for-github@v2
        with:
          workdir: dotnet
          cmds: do buildResult
      - name: Run dotnet app
        run: './dotnet/out/dotnet'
  dotnet-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: dotnet build
        uses: dagger/dagger-for-github@v2
        with:
          workdir: dotnet
          cmds: do push