name: go

on:
  push:
    paths:
      - "go/**"

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: go build
        uses: dagger/dagger-for-github@v2
        with:
          workdir: go
          cmds: do buildResult
      - name: Run go app
        run: './go/hello'