name: todoapp

on:
  push:
    branches:
      - '**'

env:
  APP_NAME: todoapp-dagger-tomas
  NETLIFY_TEAM: tomas-mota
  NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  DAGGER_LOG_FORMAT: plain

jobs:
  todoapp:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v2
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          workdir: todoapp
          cmds: do deploy
      - name: 'Print App Url'
        run: 'echo https://${{env.APP_NAME}}.netlify.app'
  todoapp:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v2
        with:
          workdir: samples
          cmds: do write
      - name: 'Read'
        run: 'cat bla/hello.txt'
